Task 2 - Model Building and Training

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from Data_Analysis_and_Preprocessing import load_data,logistic_regression,decision,RandomForest,Gradient_Boosting
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
from tensorflow import keras
from tensorflow.keras import layers

In [2]:
df_Fraud=load_data(r'C:\Users\ASUS VIVO\Desktop\week_8 and 9\Week_8_and_9\data\df_Fraud.csv')
df_Fraud.drop('Unnamed: 0',axis=1,inplace=True)
df_creditcard=load_data(r'C:\Users\ASUS VIVO\Desktop\week_8 and 9\Week_8_and_9\data\df_creditcard.csv')

In [3]:
df_Fraud.head()

,user_id,signup_time,purchase_time,purchase_value,device_id,age,ip_address,class,hour_of_day,day_of_week,transaction_frequency,transaction_velocity,browser_FireFox,browser_IE,browser_Opera,browser_Safari,sex_M,source_Direct,source_SEO
0,22058,2015-02-24 22:55:49,2015-04-18 02:47:11,0.172414,QVPSPJUOCKZAR,0.362069,0.170603,0.0,0.086957,0.833333,0.0,0.0,False,False,False,False,True,False,True
1,333320,2015-06-07 20:39:50,2015-06-08 01:38:54,0.048276,EOGFQPIZPYXFZ,0.603448,0.081554,0.0,0.043478,0.000000,0.0,0.0,False,False,False,False,False,False,False
2,1359,2015-01-01 18:52:44,2015-01-01 18:52:45,0.041379,YSSKYOSJHPPLJ,0.603448,0.610371,1.0,0.782609,0.500000,0.0,0.0,False,False,True,False,True,False,True
3,150084,2015-04-28 21:13:25,2015-05-04 13:54:50,0.241379,ATGTXKYKUDUQN,0.396552,0.894219,0.0,0.565217,0.000000,0.0,0.0,False,False,False,True,True,False,True
4,221365,2015-07-21 07:09:52,2015-09-09 18:40:53,0.206897,NAUITBZFJKHWW,0.465517,0.096752,0.0,0.782609,0.333333,0.0,0.0,False,False,False,True,True,False,False

In [4]:
df_creditcard.head()

,Unnamed: 0,Time,V1,V2,V3,V4,V5,V6,V7,V8,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [5]:

X = df_Fraud.drop('class', axis=1)
y = df_Fraud['class']


X_train_Fraud, X_test_Fraud, y_train_Fraud, y_test_Fraud = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:

X = df_creditcard.drop('Class', axis=1)
y = df_creditcard['Class']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Logistic Regression

In [7]:
logistic_regression(X_train, X_test, y_train, y_test)

Logistic Regression Accuracy: 0.9989602791386177

c:\Users\ASUS VIVO\.conda\envs\me\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Decision Tree

In [8]:
decision(X_train, X_test, y_train, y_test)

Decision Tree Accuracy: 0.9990131463010609

Random Forest

In [9]:
RandomForest(X_train, X_test, y_train, y_test)

Random Forest Accuracy: 0.9995065731505305

Gradient Boosting

In [10]:
Gradient_Boosting(X_train, X_test, y_train, y_test)

Gradient Boosting Accuracy: 0.9993127268882388